-- Crear tabla de noticias
create table public.noticias (
  id bigint generated by default as identity primary key,
  titulo text not null,
  resumen text,
  contenido text,
  imagen_url text,
  categoria text check (categoria in ('Académico', 'Logros', 'Anuncio', 'Tecnología', 'Eventos', 'Otro')),
  fecha_publicacion date default current_date,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Habilitar Row Level Security (RLS)
alter table public.noticias enable row level security;

-- Crear políticas de seguridad

-- 1. Permitir lectura pública (cualquiera puede ver las noticias)
create policy "Noticias son públicas"
  on public.noticias for select
  using ( true );

-- 2. Permitir todo a los administradores (insertar, actualizar, eliminar)
-- Nota: Esto asume que tienes una forma de identificar admins. 
-- Por simplicidad en este demo, permitiremos escritura a usuarios autenticados, 
-- pero idealmente deberías verificar el rol.
create policy "Admins pueden gestionar noticias"
  on public.noticias for all
  using ( auth.role() = 'authenticated' );
